import { useState } from 'react';
const email = import.meta.env.VITE_CONTACT_EMAIL?.trim();
const instagram = import.meta.env.VITE_INSTAGRAM_URL?.trim();
const phone = import.meta.env.VITE_WHATSAPP_NUMBER?.replace(/\D/g, '');
export default function Contact({ topic, items }) {
 const [draft,setDraft] = useState(`Hello THEWANTEND,\n\nI’m interested in ${topic || 'a custom frame'}.${items ? `\n\nMy bag:\n${items}` : ''}\n\nMy idea / occasion:\n\nPlease help me confirm the design, price and UAE delivery. I’d like to approve a preview before the frame is built.`);
 const [status,setStatus] = useState('');
 function save(){ const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='THEWANTEND-enquiry.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Enquiry saved to your device. It has not been sent.'); }
 return <div className="shop-copy"><p>Your idea starts here.</p><p className="shop-muted">{email || phone ? 'Tell us what you have in mind. We’ll confirm options, price and delivery before your order.' : 'Our contact channels are coming soon. You can prepare and save your enquiry below; nothing is sent or ordered through this preview.'}</p><div className="contact-channels">{email ? <a href={`mailto:${email}?subject=${encodeURIComponent('THEWANTEND — '+topic)}&body=${encodeURIComponent(draft)}`}>Email <span>{email} ↗</span></a> : <div>Email <span>To be announced</span></div>}{phone ? <a href={`https://wa.me/${phone}?text=${encodeURIComponent(draft)}`} target="_blank" rel="noreferrer">WhatsApp <span>Start a conversation ↗</span></a> : <div>WhatsApp <span>To be announced</span></div>}{instagram && /^https:\/\/(www\.)?instagram\.com\//.test(instagram) ? <a href={instagram} target="_blank" rel="noreferrer">Instagram <span>Visit our page ↗</span></a> : <div>Instagram <span>To be announced</span></div>}</div><label className="shop-muted" htmlFor="enquiry-draft">Your enquiry draft</label><textarea id="enquiry-draft" className="draft-area" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="shop-primary" onClick={save}>SAVE ENQUIRY DRAFT <span>↓</span></button><p className="contact-status" role="status">{status}</p></div>;
}
